language: scala

notifications:
  email: false
  
scala:
- 2.10.6

after_success:
- sbt "set deployHubBdio := false" buildBom
- bash <(curl -s https://copilot.blackducksoftware.com/bash/travis) ./target/blackduck/*_bdio.jsonld
