language: scala

scala:
- 2.10.6

after_success:
  - export COPILOT_DETECT_VERSION=1.1.0-SNAPSHOT
  - export DETECT_USE_SNAPSHOT=1
  - bash <(curl -s https://copilot-valid.blackducksoftware.com/ci/travis/scripts/upload)
